# build and make
name: app build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
        - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    # if: false # disable build
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout env
      uses: actions/checkout@v2.3.4
      with:
        repository: soundshed/soundshed-private
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: SET WIN_CODE_SIGNING_P12 = WebprofusionPty2020.p12
    - run: copy env.ts src /y
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run make
      env: 
        WIN_CODE_SIGN_PWD: ${{ secrets.WIN_CODE_SIGNING_PWD }} 
   
  build_linux_ubuntu:
    if: false 
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: sudo apt-get install build-essential libbluetooth-dev
    - run: echo $ENV_SETTINGS > src/env.ts
      env: 
        ENV_SETTINGS: ${{ secrets.ENV_SETTINGS }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run make
    - name: upload
      uses: actions/upload-artifact@v2
      with: 
          name: soundshed-linux-x64
          path: out/make/zip/linux/x64/*.zip
     
  build_macos:
    if: false 
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo $ENV_SETTINGS > src/env.ts
      env: 
        ENV_SETTINGS: ${{ secrets.ENV_SETTINGS }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run make
      
    - name: upload
      uses: actions/upload-artifact@v2
      with: 
          name: soundshed-macos-x64
          path: out/make/zip/darwin/x64/*.zip
      

