# build and make
name: app build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
        - '*'
  pull_request:
    branches: [ main ]

jobs:
  build_windows:
    # if: false # disable build
    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout App
      uses: actions/checkout@v2.3.4
      with:
        # Repository name with owner. For example, actions/checkout
        repository: soundshed/soundshed-app
        path: app-public
    
    - name: Checkout env
      uses: actions/checkout@v2.3.4
      with:
        repository: soundshed/soundshed-private
        path: app-private
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
        copy app-private\env.ts app-public\src     
        cd app-public
        npm install
        npm run build
        npm run make
      env:
        WIN_CODE_SIGNING_P12: ..\app-private\signing.pfx
        WIN_CODE_SIGNING_PWD: ${{ secrets.WIN_CODE_SIGN_PWD }}
        
    - name: upload
      uses: actions/upload-artifact@v2
      with: 
          name: soundshed-win-x64
          path: app-public/out/make/squirrel.windows/x64/*
   
  build_linux_ubuntu:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout App
      uses: actions/checkout@v2.3.4
      with:
        # Repository name with owner. For example, actions/checkout
        repository: soundshed/soundshed-app
        path: app-public
    
    - name: Checkout env
      uses: actions/checkout@v2.3.4
      with:
        repository: soundshed/soundshed-private
        path: app-private
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: sudo apt-get install build-essential libbluetooth-dev
  
    - run: |
        cp app-private/env.ts app-public/src     
        cd app-public
        npm install
        npm run build
        npm run make

    - name: upload
      uses: actions/upload-artifact@v2
      with: 
          name: soundshed-linux-x64
          path: app-public/out/make/zip/linux/x64/*.zip
     
  build_macos:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout App
      uses: actions/checkout@v2.3.4
      with:
        # Repository name with owner. For example, actions/checkout
        repository: soundshed/soundshed-app
        path: app-public
    
    - name: Checkout env
      uses: actions/checkout@v2.3.4
      with:
        repository: soundshed/soundshed-private
        path: app-private
        token: ${{ secrets.PAT_TOKEN }}
        
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - run: |
        cp app-private/env.ts app-public/src     
        cd app-public
        npm install
        npm run build
        npm run make
      
    - name: upload
      uses: actions/upload-artifact@v2
      with: 
          name: soundshed-macos-x64
          path: app-public/out/make/zip/darwin/x64/*.zip
          
  publish:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download workflow artifact
      # You may pin to the exact commit or the version.
      # uses: dawidd6/action-download-artifact@8c96194455d424a24437ec57817e0aa1a1d72adb
      uses: dawidd6/action-download-artifact@v2.12.0
      with:
        # Workflow name
        workflow: build.yml
        workflow_conclusion: success
        github_token: ${{ secrets.PAT_TOKEN }}
        
    - name: Display structure of downloaded files
      run: ls -R
    
    - name: Create Release
      # You may pin to the exact commit or the version.
      # uses: ncipollo/release-action@4b71ee3b25951e6098e7434cdc485edc5b3adab2
      uses: ncipollo/release-action@v1.7.3
      with:
        # An optional flag which indicates if we should update a release if it already exists. Defaults to false.
        allowUpdates: true
        draft: true
        artifacts: "soundshed-linux-x64/*, soundshed-macos-x64/*, soundshed-win-x64/*"
        token: ${{ secrets.GITHUB_TOKEN }}
      

